---
- name: Install nginx.
  hosts: webservers
  remote_user: vagrant
  become: true

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: latest
        update_cache: true
        
    - name: Enable service NGINX and state started
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
