---
- hosts: all
  become: true
  tasks:
    - name: Install net-tools VIM.
      apt: name={{item}} state=latest update_cache=true
      with_items:
        - net-tools
        - vim

    - name: Create inventory.
      local_action: lineinfile
        dest="../hosts"
        regexp={{ ansible_facts.eth1.ipv4.address }}
        insertafter="[webservers]" line={{ ansible_facts.eth1.ipv4.address }}