---
- name: install nginx.
  hosts: webservers
  remote_user: user
  become: yes

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: latest
        update_cache: yes
        
    - name: Enable deamon NGINX
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
